name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          path: "./DerzPlates"
          filename: "DerzPlates.zip"
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "DerzPlates.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
